# Generated by Django 2.2.1 on 2019-05-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=20)),
                ('bname', models.CharField(max_length=100)),
                ('bemail', models.EmailField(max_length=254)),
                ('bconatact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'blogger',
            },
        ),
    ]
