# Generated by Django 2.2.1 on 2019-05-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190528_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='image',
        ),
    ]
