# Generated by Django 2.2.1 on 2019-06-04 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_travel_type_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_title', models.CharField(max_length=200)),
                ('food_description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_category', models.CharField(max_length=200)),
                ('food_picture', models.ImageField(null=True, upload_to='images/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='food_category',
            field=models.ManyToManyField(to='blog.Food'),
        ),
    ]
