# Generated by Django 2.2.4 on 2019-09-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190604_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='NluUserAnalyticsTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(blank=True, max_length=255, null=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('bot_id', models.BigIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=5, null=True)),
                ('sentiment', models.IntegerField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, max_length=255, null=True)),
                ('user_feedback', models.CharField(blank=True, max_length=50, null=True)),
                ('unhandled', models.BooleanField(blank=True, null=True)),
                ('assigned', models.BooleanField(blank=True, null=True)),
                ('assigned_to', models.BigIntegerField(blank=True, null=True)),
                ('agent_transfer', models.BooleanField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.IntegerField(blank=True, null=True)),
                ('intent_id', models.IntegerField()),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('login_id', models.TextField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=200, null=True)),
                ('user_input_feedback', models.TextField(blank=True, null=True)),
                ('bot_uid', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('masked', models.BooleanField(blank=True, null=True)),
                ('is_greeting', models.BooleanField()),
            ],
            options={
                'db_table': 'nlu_user_analytics_testing',
                'managed': False,
            },
        ),
    ]
