# Generated by Django 2.2.4 on 2019-09-09 04:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190905_0555'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('all_posts', django.db.models.manager.Manager()),
            ],
        ),
    ]
