# Generated by Django 2.2.5 on 2019-09-11 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190911_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
